# Generated by Django 2.1.3 on 2018-11-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ih_area_info',
            fields=[
                ('ai_area_id', models.AutoField(primary_key=True, serialize=False, verbose_name='区域ID')),
                ('ai_name', models.CharField(max_length=32, verbose_name='区域名称')),
                ('ai_ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '房源区域表',
            },
        ),
        migrations.CreateModel(
            name='ih_facility_catelog',
            fields=[
                ('fc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('fc_name', models.CharField(max_length=32, verbose_name='设施名称')),
                ('fc_ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设施型录表',
            },
        ),
        migrations.CreateModel(
            name='ih_house_facility',
            fields=[
                ('hf_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('hf_facility_id', models.IntegerField(verbose_name='房屋设施')),
                ('hf_ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '房屋设施表',
            },
        ),
        migrations.CreateModel(
            name='ih_house_image',
            fields=[
                ('hi_image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片ID')),
                ('hi_url', models.CharField(max_length=256, verbose_name='图片url')),
                ('hi_ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '房屋图片表',
            },
        ),
        migrations.CreateModel(
            name='ih_house_info',
            fields=[
                ('hi_house_id', models.AutoField(primary_key=True, serialize=False, verbose_name='房屋ID')),
                ('hi_title', models.CharField(max_length=64, verbose_name='房屋名称')),
                ('hi_price', models.IntegerField(default='0', verbose_name='房屋价格，单位分')),
                ('hi_address', models.CharField(default='', max_length=512, verbose_name='地址')),
                ('hi_room_count', models.IntegerField(default='1', verbose_name='房间数')),
                ('hi_acreage', models.IntegerField(default='0', verbose_name='房屋面积')),
                ('hi_house_unit', models.CharField(default='', max_length=32, verbose_name='房屋户型')),
                ('hi_capacity', models.IntegerField(default='1', verbose_name='容纳人数')),
                ('hi_beds', models.CharField(default='', max_length=64, verbose_name='床的配置')),
                ('hi_deposit', models.IntegerField(default='0', verbose_name='押金，单位分')),
                ('hi_min_days', models.IntegerField(default='1', verbose_name='最短入住时间')),
                ('hi_max_days', models.IntegerField(default='0', verbose_name='最长入住时间，0-不限制')),
                ('hi_order_count', models.IntegerField(default='0', verbose_name='下单数量')),
                ('hi_verify_status', models.IntegerField(db_index=True, default='0', verbose_name='审核状态，0-待审核，1-审核未通过，2-审核通过')),
                ('hi_online_status', models.IntegerField(db_index=True, default='1', verbose_name='0-下线，1-上线')),
                ('hi_index_image_url', models.CharField(max_length=256, null=True, verbose_name='房屋主图片url')),
                ('hi_utime', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('hi_ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('hi_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ih_area_info')),
            ],
            options={
                'verbose_name': '房屋信息表',
            },
        ),
        migrations.CreateModel(
            name='ih_order_info',
            fields=[
                ('oi_order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('oi_begin_date', models.DateField(verbose_name='入住时间')),
                ('oi_end_date', models.DateField(verbose_name='离开时间')),
                ('oi_days', models.IntegerField(verbose_name='入住天数')),
                ('oi_house_price', models.IntegerField(verbose_name='房屋单价，单位分')),
                ('oi_amount', models.IntegerField(verbose_name='订单金额，单位分')),
                ('oi_status', models.IntegerField(db_index=True, default='0', verbose_name='订单状态，0-待接单，1-待支付，2-已支付，3-待评价，4-已完成，5-已取消，6-拒接单')),
                ('oi_comment', models.TextField(null=True, verbose_name='订单评论')),
                ('oi_utime', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('oi_ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('oi_house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ih_house_info')),
            ],
            options={
                'verbose_name': '订单表',
            },
        ),
        migrations.CreateModel(
            name='ih_user_profile',
            fields=[
                ('up_user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('up_name', models.CharField(max_length=32, unique=True, verbose_name='昵称')),
                ('up_mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('up_passwd', models.CharField(max_length=64, verbose_name='密码')),
                ('up_real_name', models.CharField(max_length=32, null=True, verbose_name='真实姓名')),
                ('up_id_card', models.CharField(max_length=20, null=True, verbose_name='身份证号')),
                ('up_avatar', models.CharField(max_length=128, null=True, verbose_name='用户头像')),
                ('up_admin', models.BooleanField(default='0', verbose_name='是否是管理员，0-不是，1-是')),
                ('up_utime', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('up_ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户信息表',
            },
        ),
        migrations.AddField(
            model_name='ih_order_info',
            name='oi_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ih_user_profile'),
        ),
        migrations.AddField(
            model_name='ih_house_info',
            name='hi_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ih_user_profile'),
        ),
        migrations.AddField(
            model_name='ih_house_image',
            name='hi_house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ih_house_info'),
        ),
        migrations.AddField(
            model_name='ih_house_facility',
            name='hf_house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ih_house_info'),
        ),
    ]
