# Generated by Django 2.1 on 2018-11-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ih_user_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_token', models.CharField(max_length=64)),
                ('up_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ih_user_profile')),
            ],
            options={
                'verbose_name': 'Token表',
            },
        ),
    ]
